service: apollo-lambda
provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

functions:
  graphql:
    handler: dist/index.handler
    events:
      - http:
          method: any
          path: graphql

